export const GET_ANTENNA_LIST = 'GET_ANTENNA_LIST';
export const GET_ANTENNA_LIST_SUCCESS = 'GET_ANTENNA_LIST_SUCCESS';
export const GET_ANTENNA_LIST_FAILURE = 'GET_ANTENNA_LIST_FAILURE';

export const UPDATE_ANTENNA_HEALTH = 'UPDATE_ANTENNA_HEALTH';
export const ANTENNA_HEALTH_CALL_CHANGE_STATUS = 'ANTENNA_HEALTH_CALL_CHANGE_STATUS';
export const ANTENNA_HEALTH_CALL_ERR = 'ANTENNA_HEALTH_CALL_ERR';
